import { createSlice, createAsyncThunk, createEntityAdapter } from '@reduxjs/toolkit';
import { fetchPostsFromAPI } from './postsAPI';

// createEntityAdapter provides a normalized state structure: { ids: [], entities: {} }
// This avoids data duplication and makes lookups O(1).
const postsAdapter = createEntityAdapter({
  // By default it looks for an 'id' field on entities.
  // We can sort them if we want, but we'll stick to insertion order for simplicity.
});

// The initial state includes the adapter's initial state (ids, entities) 
// plus any extra fields we need (status, error).
const initialState = postsAdapter.getInitialState({
  status: 'idle', // 'idle' | 'loading' | 'succeeded' | 'failed'
  error: null,
});

// createAsyncThunk standardizes the async request lifecycle.
// It will automatically dispatch 'pending', 'fulfilled', and 'rejected' actions.
export const fetchPosts = createAsyncThunk('posts/fetchPosts', async () => {
  const response = await fetchPostsFromAPI();
  return response;
});

const postsSlice = createSlice({
  name: 'posts',
  initialState,
  reducers: {
    // Synchronous reducers for CRUD operations
    addPost: postsAdapter.addOne, // Adds a single post to the normalized state
    updatePost: postsAdapter.updateOne, // Updates a post (expects { id, changes })
    deletePost: postsAdapter.removeOne, // Removes a post by id
    
    // Custom reducer to increment likes
    likePost(state, action) {
      // Immer allows us to write "mutating" logic safely.
      const id = action.payload;
      const existingPost = state.entities[id];
      if (existingPost) {
        existingPost.likes += 1;
      }
    },
  },
  extraReducers: (builder) => {
    // Handle the lifecycle actions generated by fetchPosts thunk
    builder
      .addCase(fetchPosts.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.status = 'succeeded';
        // Add the fetched posts to the state using the adapter
        postsAdapter.setAll(state, action.payload);
      })
      .addCase(fetchPosts.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.error.message;
      });
  },
});

export const { addPost, updatePost, deletePost, likePost } = postsSlice.actions;

export default postsSlice.reducer;

// Export the customized selectors for this adapter.
// These selectors are memoized and automatically know how to read from { ids, entities }
export const {
  selectAll: selectAllPosts,
  selectById: selectPostById,
  selectIds: selectPostIds,
} = postsAdapter.getSelectors((state) => state.posts);
